---
before:
  hooks:
    - "go mod tidy"
    - "./scripts/completions.sh"

builds:
  - id: "cli"
    env:
      - "CGO_ENABLED=0"
    goos:
      - "linux"
      - "windows"
      - "darwin"
    main: "./internal/cmd/kwcerts"
    binary: "kwcerts"
    ldflags:
      - "-s -w -X github.com/klearwave/internal/cmd/kwcerts/version.version={{ .Version }} -extldflags '-static'"

archives:
  - name_template: >-
      {{ .ProjectName }}_v{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - "README.md"
      - "LICENSE"
      - "completions/*"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-snapshot-{{ .ShortCommit }}"

changelog:
  sort: "asc"
  use: "github"
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^test(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^chore(\(.*\))?:'
      - '^build(\(.*\))?:'

release:
  replace_existing_artifacts: true
  make_latest: true
  include_meta: true

brews:
  - name: "kwcerts"
    repository:
      owner: "klearwave"
      name: "homebrew-tap"
      token: "{{ .Env.GITHUB_TOKEN }}"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: "goreleaserbot"
      email: "goreleaser+no-replay@klearwave.io"

    # Folder inside the repository to put the formula.
    # Default is the root folder.
    directory: "Formula"

    # Your app's homepage.
    # Default is empty.
    homepage: "https://github.com/klearwave"

    # Template of your app's description.
    # Default is empty.
    description: "Utility to manage self-signed certificates."

    # SPDX identifier of your app's license.
    # Default is empty.
    license: "Apache-2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: "auto"

    # Packages your package depends on.
    dependencies: []

    install: |-
      bin.install "kwcerts"

    # So you can `brew test` your formula.
    # Default is empty.
    test: |
      system "#{bin}/kwcerts version"
